quarkus:
  log:
    level: INFO
    category:
      "org.incept5":
        level: DEBUG
    console:
      format: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %-5p %H -- [%X{traceId}/%X{spanId}/%X{correlationId}] - [%c{3.}] (%t-%t{id}) %s%e%n"
    json:
      console:
        enable: true
  native:
    enabled: false