/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.velostone.correlation

import org.slf4j.MDC
import java.util.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class CorrelationTest {

    companion object {
        val logger = org.slf4j.LoggerFactory.getLogger(CorrelationTest::class.java)
    }

    @Test fun correlationIdTest() {

        logger.info("CorrelationIdTest")

        val id = UUID.randomUUID().toString()
        CorrelationId.setId(id)

        assertEquals(id, CorrelationId.getId(), "CorrelationId should be set")
        assertEquals(id.toString(), MDC.get("correlationId"), "MDC should contain the correlationId")

        CorrelationId.clear()
        assertEquals(null, MDC.get("correlationId"), "MDC should be null")

        val id2 = CorrelationId.getId()
        assertNotNull(id2, "CorrelationId should be populated automatically")
        assertEquals(id2, CorrelationId.getId(), "CorrelationId should be set")

    }
}
