/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.velostone.correlation

import org.slf4j.MDC
import java.util.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class TraceIdTest {

    companion object {
        val logger = org.slf4j.LoggerFactory.getLogger(TraceIdTest::class.java)
    }

    @Test fun traceIdTest() {

        logger.info("TraceIdTest")

        val id = UUID.randomUUID().toString()
        TraceId.setId(id)

        assertEquals(id, TraceId.getId(), "TraceId should be set")
        assertEquals(id.toString(), MDC.get("traceId"), "MDC should contain the traceId")

        TraceId.clear()
        assertEquals(null, MDC.get("traceId"), "MDC should be null")

        val id2 = TraceId.getId()
        assertNotNull(id2, "TraceId should be populated automatically")
        assertEquals(id2, TraceId.getId(), "TraceId should be set")

    }
}
